/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as WelcomeSplatRouteImport } from './routes/welcome/$'
import { Route as AuthenticatedSidebarRouteImport } from './routes/_authenticated/_sidebar'
import { Route as AuthenticatedSidebarIndexRouteImport } from './routes/_authenticated/_sidebar/index'
import { Route as AuthenticatedSidebarChatsIndexRouteImport } from './routes/_authenticated/_sidebar/chats/index'
import { Route as AuthenticatedSidebarCalendarIndexRouteImport } from './routes/_authenticated/_sidebar/calendar/index'
import { Route as AuthenticatedSidebarAccountSettingsSplatRouteImport } from './routes/_authenticated/_sidebar/account-settings/$'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeSplatRoute = WelcomeSplatRouteImport.update({
  id: '/welcome/$',
  path: '/welcome/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSidebarRoute = AuthenticatedSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSidebarIndexRoute =
  AuthenticatedSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarChatsIndexRoute =
  AuthenticatedSidebarChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarCalendarIndexRoute =
  AuthenticatedSidebarCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarAccountSettingsSplatRoute =
  AuthenticatedSidebarAccountSettingsSplatRouteImport.update({
    id: '/account-settings/$',
    path: '/account-settings/$',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedSidebarIndexRoute
  '/welcome/$': typeof WelcomeSplatRoute
  '/account-settings/$': typeof AuthenticatedSidebarAccountSettingsSplatRoute
  '/calendar/': typeof AuthenticatedSidebarCalendarIndexRoute
  '/chats/': typeof AuthenticatedSidebarChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedSidebarIndexRoute
  '/welcome/$': typeof WelcomeSplatRoute
  '/account-settings/$': typeof AuthenticatedSidebarAccountSettingsSplatRoute
  '/calendar': typeof AuthenticatedSidebarCalendarIndexRoute
  '/chats': typeof AuthenticatedSidebarChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_sidebar': typeof AuthenticatedSidebarRouteWithChildren
  '/welcome/$': typeof WelcomeSplatRoute
  '/_authenticated/_sidebar/': typeof AuthenticatedSidebarIndexRoute
  '/_authenticated/_sidebar/account-settings/$': typeof AuthenticatedSidebarAccountSettingsSplatRoute
  '/_authenticated/_sidebar/calendar/': typeof AuthenticatedSidebarCalendarIndexRoute
  '/_authenticated/_sidebar/chats/': typeof AuthenticatedSidebarChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome/$'
    | '/account-settings/$'
    | '/calendar/'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/welcome/$' | '/account-settings/$' | '/calendar' | '/chats'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_sidebar'
    | '/welcome/$'
    | '/_authenticated/_sidebar/'
    | '/_authenticated/_sidebar/account-settings/$'
    | '/_authenticated/_sidebar/calendar/'
    | '/_authenticated/_sidebar/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  WelcomeSplatRoute: typeof WelcomeSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/$': {
      id: '/welcome/$'
      path: '/welcome/$'
      fullPath: '/welcome/$'
      preLoaderRoute: typeof WelcomeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_sidebar': {
      id: '/_authenticated/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSidebarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_sidebar/': {
      id: '/_authenticated/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSidebarIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/chats/': {
      id: '/_authenticated/_sidebar/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedSidebarChatsIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/calendar/': {
      id: '/_authenticated/_sidebar/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedSidebarCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/account-settings/$': {
      id: '/_authenticated/_sidebar/account-settings/$'
      path: '/account-settings/$'
      fullPath: '/account-settings/$'
      preLoaderRoute: typeof AuthenticatedSidebarAccountSettingsSplatRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
  }
}

interface AuthenticatedSidebarRouteChildren {
  AuthenticatedSidebarIndexRoute: typeof AuthenticatedSidebarIndexRoute
  AuthenticatedSidebarAccountSettingsSplatRoute: typeof AuthenticatedSidebarAccountSettingsSplatRoute
  AuthenticatedSidebarCalendarIndexRoute: typeof AuthenticatedSidebarCalendarIndexRoute
  AuthenticatedSidebarChatsIndexRoute: typeof AuthenticatedSidebarChatsIndexRoute
}

const AuthenticatedSidebarRouteChildren: AuthenticatedSidebarRouteChildren = {
  AuthenticatedSidebarIndexRoute: AuthenticatedSidebarIndexRoute,
  AuthenticatedSidebarAccountSettingsSplatRoute:
    AuthenticatedSidebarAccountSettingsSplatRoute,
  AuthenticatedSidebarCalendarIndexRoute:
    AuthenticatedSidebarCalendarIndexRoute,
  AuthenticatedSidebarChatsIndexRoute: AuthenticatedSidebarChatsIndexRoute,
}

const AuthenticatedSidebarRouteWithChildren =
  AuthenticatedSidebarRoute._addFileChildren(AuthenticatedSidebarRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSidebarRoute: typeof AuthenticatedSidebarRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSidebarRoute: AuthenticatedSidebarRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  WelcomeSplatRoute: WelcomeSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
